# Generated by Django 3.2.3 on 2024-05-27 16:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_patronymic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('following', django.db.models.expressions.F('follower')), _negated=True), name='no_self_subscription'),
        ),
    ]
